# Generated by Django 4.2.24 on 2025-10-23 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='obras', verbose_name='Imagen')),
                ('medio', models.CharField(choices=[('Lienzo', 'Lienzo'), ('Impresiones', 'Impresiones')], default='Lienzo', max_length=50, verbose_name='Medio de Obra')),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Normal', 'Normal'), ('En Tendencia', 'En Tendencia'), ('Destacado', 'Destacado')], default='Normal', max_length=50, verbose_name='Estado del producto')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de publicación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición')),
                ('etiquetas', models.ManyToManyField(to='catalogo.etiqueta', verbose_name='etiquetas')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
    ]
