# Generated by Django 4.2.24 on 2025-11-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='stock',
        ),
    ]
