# Generated by Django 4.2.24 on 2025-11-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_obra_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='descripcion',
            field=models.CharField(default='', max_length=70, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='medio',
            field=models.CharField(choices=[('Lienzo', 'Lienzo'), ('Mural', 'Mural'), ('Impresiones', 'Impresiones')], default='Lienzo', max_length=50, verbose_name='Medio de Obra'),
        ),
    ]
