# Generated by Django 4.2.24 on 2025-11-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_etiqueta_descripcion_alter_obra_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado'), ('Reservado', 'Reservado')], default='Normal', max_length=50, verbose_name='Estado del producto'),
        ),
    ]
