# Generated by Django 4.2.24 on 2025-12-04 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_obra_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='obra',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Última vez editado'),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fuente_de_texto', models.CharField(choices=[('Base', 'base'), ('Oswald', 'oswald')], default='base', max_length=20, verbose_name='Fuente de texto')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Última vez editado')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.obra', verbose_name='Cita de publicación')),
            ],
        ),
    ]
