# Generated by Django 5.2.6 on 2025-12-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_remove_obra_descripcion_alter_obra_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name': 'publicación', 'verbose_name_plural': 'publicaciones'},
        ),
    ]
