# Generated by Django 5.2.7 on 2025-12-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_publicacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fuente_de_texto',
            field=models.CharField(choices=[('base', 'base'), ('oswald', 'oswald')], default='base', max_length=20, verbose_name='Fuente de texto'),
        ),
    ]
