# Generated by Django 5.2.7 on 2025-12-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_publicacion_fuente_de_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='obras/', verbose_name='Imagen'),
        ),
    ]
