# Generated by Django 5.2.7 on 2025-12-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_obra_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
