# Generated by Django 5.2.7 on 2025-12-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_obra_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
