# Generated by Django 5.2.7 on 2025-12-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alter_obra_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='obras/', verbose_name='Imagen'),
        ),
    ]
