# Generated by Django 4.2.24 on 2025-12-04 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_usuario_ap_mat_usuario_ap_pat_usuario_nombre_and_more'),
        ('catalogo', '0006_alter_publicacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('estado', models.CharField(choices=[('En proceso', 'En proceso'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Normal', max_length=50, verbose_name='Estado del producto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('ult_actualizado', models.DateTimeField(auto_now=True, verbose_name='Última vez actualizado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Cliente')),
                ('lista_productos', models.ManyToManyField(to='catalogo.obra', verbose_name='Lista de productos del pedido')),
            ],
        ),
    ]
