# Generated by Django 4.2.24 on 2025-12-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletadecompra',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Normal', max_length=50, verbose_name='Estado del producto'),
        ),
    ]
