# Generated by Django 4.2.24 on 2025-12-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_boletadecompra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletadecompra',
            name='id_sesion_pago',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID de sesión del proveedor de pago'),
        ),
        migrations.AddField(
            model_name='boletadecompra',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('transferencia', 'Transferencia bancaria'), ('efectivo', 'Pago en efectivo'), ('mercadopago', 'MercadoPago')], max_length=50, verbose_name='Método de pago seleccionado'),
        ),
        migrations.AddField(
            model_name='boletadecompra',
            name='proveedor_pago',
            field=models.CharField(blank=True, max_length=50, verbose_name='Proveedor de pago'),
        ),
        migrations.AlterField(
            model_name='boletadecompra',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='En proceso', max_length=50, verbose_name='Estado del producto'),
        ),
    ]
