# Generated by Django 4.2.24 on 2025-12-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_boletadecompra_id_sesion_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletadecompra',
            name='direccion',
            field=models.CharField(default='Direccion5', max_length=100),
            preserve_default=False,
        ),
    ]
