# Generated by Django 4.2.24 on 2025-12-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ap_mat',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ap_pat',
            field=models.CharField(default='Sin Especificar', max_length=40, verbose_name='Apellido Paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='Sin Especificar', max_length=40, verbose_name='Nombre de usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=40, verbose_name='Username'),
        ),
    ]
