# Generated by Django 4.2.24 on 2025-12-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_ap_mat_usuario_ap_pat_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ap_mat',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ap_pat',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='Erre', max_length=200, verbose_name='Apellidos'),
            preserve_default=False,
        ),
    ]
